UPDATE menu_items
SET
    name = /*name*/'商品名',
    description = COALESCE(/*description*/'', ''),
    price = /*price*/0,
    cost_price = GREATEST(0, /*cost_price*/0),
    tax_rate = /*tax_rate*/10,
    image_url = NULLIF(/*image_url*/'', ''),
    category_id = /*category_id*/'cat-coffee',
    display_order = /*display_order*/0,
    active = /*active*/TRUE,
    sold_out = /*sold_out*/FALSE,
    track_stock = COALESCE(/*track_stock*/FALSE, FALSE),
    stock_quantity = GREATEST(0, /*stock_quantity*/0),
    low_stock_threshold = GREATEST(0, /*low_stock_threshold*/0),
    allergy_note = COALESCE(/*allergy_note*/'', ''),
    updated_at = CURRENT_TIMESTAMP
WHERE id = /*item_id*/'item-admin'
RETURNING
    id,
    category_id,
    (SELECT name FROM menu_categories WHERE id = menu_items.category_id) AS category_name,
    name,
    description,
    price,
    cost_price,
    (price - cost_price)::INTEGER AS gross_profit,
    CASE WHEN price = 0 THEN 0 ELSE ROUND(((price - cost_price)::numeric / price) * 100, 1) END AS gross_margin_rate,
    tax_rate,
    image_url,
    display_order,
    active,
    sold_out,
    track_stock,
    stock_quantity,
    low_stock_threshold,
    allergy_note,
    updated_at;
