INSERT INTO daily_cash_closures (
    id,
    business_date,
    status,
    period_started_at,
    period_ended_at,
    gross_sales_total,
    refund_total,
    net_sales_total,
    tax_total,
    cost_total,
    gross_profit,
    cash_total,
    card_total,
    qr_total,
    internal_provider_total,
    mock_provider_total,
    paid_count,
    partial_refunded_count,
    refunded_count,
    failed_count,
    cancelled_count,
    refund_count,
    closed_by_user_id,
    closed_by_user_display_name,
    closed_by_user_role,
    closed_by_terminal_code,
    closed_at,
    reopened_by_user_id,
    reopened_by_user_display_name,
    reopened_by_user_role,
    reopened_by_terminal_code,
    reopened_at,
    reopen_reason,
    note,
    created_at,
    updated_at
)
VALUES (
    /*id*/'dcc-dev',
    /*business_date*/'2026-06-25'::date,
    'closed',
    /*period_started_at*/'2026-06-25 00:00:00'::timestamp,
    /*period_ended_at*/'2026-06-25 23:59:59'::timestamp,
    /*gross_sales_total*/0,
    /*refund_total*/0,
    /*net_sales_total*/0,
    /*tax_total*/0,
    /*cost_total*/0,
    /*gross_profit*/0,
    /*cash_total*/0,
    /*card_total*/0,
    /*qr_total*/0,
    /*internal_provider_total*/0,
    /*mock_provider_total*/0,
    /*paid_count*/0,
    /*partial_refunded_count*/0,
    /*refunded_count*/0,
    /*failed_count*/0,
    /*cancelled_count*/0,
    /*refund_count*/0,
    NULLIF(/*closed_by_user_id*/'', ''),
    NULLIF(/*closed_by_user_display_name*/'', ''),
    NULLIF(/*closed_by_user_role*/'', ''),
    NULLIF(/*closed_by_terminal_code*/'', ''),
    CURRENT_TIMESTAMP,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '',
    COALESCE(NULLIF(/*note*/'', ''), ''),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (business_date) DO UPDATE SET
    status = 'closed',
    period_started_at = EXCLUDED.period_started_at,
    period_ended_at = EXCLUDED.period_ended_at,
    gross_sales_total = EXCLUDED.gross_sales_total,
    refund_total = EXCLUDED.refund_total,
    net_sales_total = EXCLUDED.net_sales_total,
    tax_total = EXCLUDED.tax_total,
    cost_total = EXCLUDED.cost_total,
    gross_profit = EXCLUDED.gross_profit,
    cash_total = EXCLUDED.cash_total,
    card_total = EXCLUDED.card_total,
    qr_total = EXCLUDED.qr_total,
    internal_provider_total = EXCLUDED.internal_provider_total,
    mock_provider_total = EXCLUDED.mock_provider_total,
    paid_count = EXCLUDED.paid_count,
    partial_refunded_count = EXCLUDED.partial_refunded_count,
    refunded_count = EXCLUDED.refunded_count,
    failed_count = EXCLUDED.failed_count,
    cancelled_count = EXCLUDED.cancelled_count,
    refund_count = EXCLUDED.refund_count,
    closed_by_user_id = EXCLUDED.closed_by_user_id,
    closed_by_user_display_name = EXCLUDED.closed_by_user_display_name,
    closed_by_user_role = EXCLUDED.closed_by_user_role,
    closed_by_terminal_code = EXCLUDED.closed_by_terminal_code,
    closed_at = CURRENT_TIMESTAMP,
    reopened_by_user_id = NULL,
    reopened_by_user_display_name = NULL,
    reopened_by_user_role = NULL,
    reopened_by_terminal_code = NULL,
    reopened_at = NULL,
    reopen_reason = '',
    note = EXCLUDED.note,
    updated_at = CURRENT_TIMESTAMP
WHERE daily_cash_closures.status = 'reopened'
RETURNING *;
