INSERT INTO inventory_movements (
    id,
    menu_item_id,
    movement_type,
    quantity_delta,
    quantity_before,
    quantity_after,
    reason,
    source_type,
    source_id,
    order_id,
    order_item_id,
    actor_user_id,
    actor_user_display_name,
    actor_user_role,
    actor_terminal_code
) VALUES (
    /*id*/'mov-dev',
    /*menu_item_id*/'item-admin',
    /*movement_type*/'manual_adjust',
    /*quantity_delta*/1,
    /*quantity_before*/0,
    /*quantity_after*/1,
    COALESCE(/*reason*/'', ''),
    NULLIF(/*source_type*/'', ''),
    NULLIF(/*source_id*/'', ''),
    NULLIF(/*order_id*/'', ''),
    NULLIF(/*order_item_id*/'', ''),
    NULLIF(/*actor_user_id*/'', ''),
    NULLIF(/*actor_user_display_name*/'', ''),
    NULLIF(/*actor_user_role*/'', ''),
    NULLIF(/*actor_terminal_code*/'', '')
)
RETURNING
    id,
    menu_item_id,
    (SELECT name FROM menu_items WHERE id = inventory_movements.menu_item_id) AS item_name,
    movement_type,
    quantity_delta,
    quantity_before,
    quantity_after,
    reason,
    source_type,
    source_id,
    order_id,
    (SELECT order_no FROM orders WHERE id = inventory_movements.order_id) AS order_no,
    order_item_id,
    actor_user_id,
    actor_user_display_name,
    actor_user_role,
    actor_terminal_code,
    occurred_at,
    created_at;
